=== PBLGrupo6/PBLGrupo6.github.io/Analisis_de_pacientes.xsd
<?xml version="1.0" encoding="utf-8"?> 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Resultados_de_los_pacientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Paciente" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Identificacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nombre" type="xs:string"/>
                                        <xs:element name="Apellido1" type="xs:string"/>
                                        <xs:element name="Apellido2" type="xs:string"/>
                                        <xs:element name="Edad" type="xs:integer"/>
                                        <xs:element name="Genero" type="xs:string"/>
                                        <xs:element name="Bloodtype" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Centro_sanitario" type="xs:string"/>
                            <xs:element name="Resultados">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Diagnostico" type="xs:string"/>
                                        <xs:element name="Especie_plasmodium" type="xs:string"/>
                                        <xs:element name="numero_parasito" type="xs:integer"/>
                                        <xs:element name="Severidad" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Procesamiento">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Imagen" type="xs:string"/>
                                        <xs:element name="Muestra" type="xs:string"/>
                                        <xs:element name="TinciÃ³n" type="xs:string"/>
                                        <xs:element name="Fecha_de_diagnostico" type="xs:string"/>
                                        <xs:element name="Modelo" type="xs:string"/>
                                        <xs:element name="Nivel_de_Confianza" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PBLGrupo6/PBLGrupo6.github.io/juan.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="Analisis_de_pacientes.xslt"?>
<Resultados_de_los_pacientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Analisis_de_pacientes.xsd">
    <Paciente id="1">
        <Identificacion>
            <Nombre>Juan</Nombre>
            <Apellido1>Castillo</Apellido1>
            <Apellido2>Villa</Apellido2>
            <Edad>30</Edad>              <!--La edad se considera un factor de riesgo-->
            <Genero>Masculino</Genero> 
            <Bloodtype>AB+</Bloodtype>
        </Identificacion>
        <Centro_sanitario>Hospital Militar Principal de Luanda</Centro_sanitario>
        <Resultados>
            <Diagnostico>Positivo en Malaria</Diagnostico>
            <Especie_plasmodium>P. falciparum</Especie_plasmodium>
            <numero_parasito>50000</numero_parasito>  <!--La enfermedad se considera grave a partir de los 10000 parásitos/µL-->
            <Severidad>Grave</Severidad>
        </Resultados>
        <Procesamiento>
            <Imagen>imagenes/20170831_234431.jpg</Imagen>
            <Muestra>Frotis fino</Muestra>
            <Tinción>Giemsa</Tinción>
            <Fecha_de_diagnostico>2505-05-05</Fecha_de_diagnostico>
            <Modelo>Modelo de Machine Learning v1.0</Modelo>
            <Nivel_de_Confianza>Media</Nivel_de_Confianza>
        </Procesamiento>   
    </Paciente>
</Resultados_de_los_pacientes>

=== PBLGrupo6/PBLGrupo6.github.io/paco.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="Analisis_de_pacientes.xslt"?>
<Resultados_de_los_pacientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Analisis_de_pacientes.xsd">
    <Paciente id="3">
        <Identificacion>
            <Nombre>Paco</Nombre>
            <Apellido1>Etxeberria</Apellido1>
            <Apellido2>Adewale</Apellido2>
            <Edad>112</Edad>
            <Genero>Masculino</Genero> 
            <Bloodtype>0-</Bloodtype>
        </Identificacion>
        <Centro_sanitario>Hospital Militar Principal de Luanda</Centro_sanitario>
        <Resultados>
            <Diagnostico>Positivo en Malaria</Diagnostico>
            <Especie_plasmodium>P. Falciparum</Especie_plasmodium>
            <numero_parasito>9999999</numero_parasito>
            <Severidad>Grave</Severidad>
        </Resultados>
        <Procesamiento>
            <Imagen>imagenes/20190723_182432.jpg</Imagen>
            <Muestra>Frotis fino</Muestra>
            <Tinción>Giemsa</Tinción>
            <Fecha_de_diagnostico>2025-05-05</Fecha_de_diagnostico>
            <Modelo>Modelo de Machine Learning v1.0</Modelo>
            <Nivel_de_Confianza>Media</Nivel_de_Confianza>
        </Procesamiento>   
    </Paciente>
</Resultados_de_los_pacientes>

=== PBLGrupo6/PBLGrupo6.github.io/ana.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="Analisis_de_pacientes.xslt"?>
<Resultados_de_los_pacientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Analisis_de_pacientes.xsd">
    <Paciente id="2">
        <Identificacion>
            <Nombre>Ana</Nombre>
            <Apellido1>Castillo</Apellido1>
            <Apellido2>Villa</Apellido2>
            <Edad>37</Edad>
            <Genero>Femenino</Genero> 
            <Bloodtype>A-</Bloodtype>
        </Identificacion>
        <Centro_sanitario>Hospital Militar Principal de Luanda</Centro_sanitario>
        <Resultados>
            <Diagnostico>Negativo en Malaria</Diagnostico>
            <Especie_plasmodium>None</Especie_plasmodium>
            <numero_parasito>0</numero_parasito>
            <Severidad>None</Severidad>
        </Resultados>
        <Procesamiento>
            <Imagen>imagenes/20170901_031213.jpg</Imagen>
            <Muestra>Frotis fino</Muestra>
            <Tinción>Giemsa</Tinción>
            <Fecha_de_diagnostico>2025-05-05</Fecha_de_diagnostico>
            <Modelo>Modelo de Machine Learning v1.0</Modelo>
            <Nivel_de_Confianza>Alta</Nivel_de_Confianza>
        </Procesamiento>   
    </Paciente>
</Resultados_de_los_pacientes>
